// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: requestHandler.proto

#include "requestHandler.pb.h"
#include "requestHandler.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace requestHandler {

static const char* RequestHandler_method_names[] = {
  "/requestHandler.RequestHandler/HandleRequest",
};

std::unique_ptr< RequestHandler::Stub> RequestHandler::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RequestHandler::Stub> stub(new RequestHandler::Stub(channel, options));
  return stub;
}

RequestHandler::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HandleRequest_(RequestHandler_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RequestHandler::Stub::HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::requestHandler::Responce* response) {
  return ::grpc::internal::BlockingUnaryCall< ::requestHandler::Request, ::requestHandler::Responce, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleRequest_, context, request, response);
}

void RequestHandler::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::requestHandler::Request, ::requestHandler::Responce, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, std::move(f));
}

void RequestHandler::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>* RequestHandler::Stub::PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::requestHandler::Responce, ::requestHandler::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>* RequestHandler::Stub::AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

RequestHandler::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RequestHandler_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RequestHandler::Service, ::requestHandler::Request, ::requestHandler::Responce, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RequestHandler::Service* service,
             ::grpc::ServerContext* ctx,
             const ::requestHandler::Request* req,
             ::requestHandler::Responce* resp) {
               return service->HandleRequest(ctx, req, resp);
             }, this)));
}

RequestHandler::Service::~Service() {
}

::grpc::Status RequestHandler::Service::HandleRequest(::grpc::ServerContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace requestHandler

