// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: requestHandler.proto
#ifndef GRPC_requestHandler_2eproto__INCLUDED
#define GRPC_requestHandler_2eproto__INCLUDED

#include "requestHandler.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace requestHandler {

// The greeting service definition.
class RequestHandler final {
 public:
  static constexpr char const* service_full_name() {
    return "requestHandler.RequestHandler";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::requestHandler::Responce* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>> AsyncHandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>>(AsyncHandleRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>> PrepareAsyncHandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>>(PrepareAsyncHandleRequestRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      virtual void HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>* AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::requestHandler::Responce>* PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::requestHandler::Responce* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>> AsyncHandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>>(AsyncHandleRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>> PrepareAsyncHandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>>(PrepareAsyncHandleRequestRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, std::function<void(::grpc::Status)>) override;
      void HandleRequest(::grpc::ClientContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>* AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::requestHandler::Responce>* PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::requestHandler::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HandleRequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status HandleRequest(::grpc::ServerContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HandleRequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleRequest(::grpc::ServerContext* context, ::requestHandler::Request* request, ::grpc::ServerAsyncResponseWriter< ::requestHandler::Responce>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HandleRequest<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HandleRequest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::requestHandler::Request, ::requestHandler::Responce>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::requestHandler::Request* request, ::requestHandler::Responce* response) { return this->HandleRequest(context, request, response); }));}
    void SetMessageAllocatorFor_HandleRequest(
        ::grpc::MessageAllocator< ::requestHandler::Request, ::requestHandler::Responce>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::requestHandler::Request, ::requestHandler::Responce>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_HandleRequest<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HandleRequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HandleRequest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HandleRequest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HandleRequest(context, request, response); }));
    }
    ~WithRawCallbackMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HandleRequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::requestHandler::Request, ::requestHandler::Responce>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::requestHandler::Request, ::requestHandler::Responce>* streamer) {
                       return this->StreamedHandleRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::requestHandler::Request* /*request*/, ::requestHandler::Responce* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandleRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::requestHandler::Request,::requestHandler::Responce>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HandleRequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HandleRequest<Service > StreamedService;
};

}  // namespace requestHandler


#endif  // GRPC_requestHandler_2eproto__INCLUDED
